In [1]:
import numpy as np
import pandas as pd

In [3]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Stack A and B vertically
stacked_vertically = np.vstack((A, B))
print("Stacked Vertically:\n", stacked_vertically)

# Stack A and B horizontally
stacked_horizontally = np.hstack((A, B))
print("Stacked Horizontally:\n", stacked_horizontally)

Stacked Vertically:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stacked Horizontally:
 [[1 2 5 6]
 [3 4 7 8]]


In [4]:
# 2. Find common elements between A and B.
common_elements = np.intersect1d(A, B)
print("Common elements between A and B:", common_elements)

Common elements between A and B: []


In [5]:
# 3. Extract all numbers from A which are within a specific range, e.g., between 5 and 10.
A = np.array([[3, 5, 8], [10, 1, 7]])
filtered_A = A[(A >= 5) & (A <= 10)]
print("Numbers from A between 5 and 10:", filtered_A)

Numbers from A between 5 and 10: [ 5  8 10  7]


In [6]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
filtered_iris_2d = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered iris_2d rows:\n", filtered_iris_2d)

Filtered iris_2d rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [7]:
# 5. From df filter the 'Manufacturer', 'Model', and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("Filtered rows (every 20th row):\n", filtered_df)

Filtered rows (every 20th row):
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [8]:
# 6. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print("DataFrame after filling missing Min.Price and Max.Price values:\n", df[['Min.Price', 'Max.Price']].head())

DataFrame after filling missing Min.Price and Max.Price values:
    Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [9]:
# 7. How to get the rows of a dataframe with row sum > 100?
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_sum_gt_100 = df_random[df_random.sum(axis=1) > 100]
print("Rows with sum > 100:\n", rows_sum_gt_100)


Rows with sum > 100:
      0   1   2   3
4   28  19  25  35
6   38  13  34  35
8   24  26  22  32
13  39  16  23  30
